# -*- coding: utf-8 -*-
"""Kaggle_Tytanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1usOIv1G1zI4yaUqVfV1RcoCj8yyXJv2P
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
ids=test['PassengerId']

def clean_data(data):
  data=data.drop(['Ticket', 'Cabin', 'Name', 'PassengerId'], axis=1)

  cols=['SibSp', 'Parch', 'Fare', 'Age']
  for col in cols:
    data[col].fillna(data[col].median(), inplace=True)

  data.Embarked.fillna('U', inplace=True)
  return data

train=clean_data(train)
test=clean_data(test)

le=preprocessing.LabelEncoder()

cols_to_replace=['Sex', 'Embarked']

for col_to_replace in cols_to_replace:
  train[col_to_replace]=le.fit_transform(train[col_to_replace])
  test[col_to_replace]=le.fit_transform(test[col_to_replace])


X = train.drop(columns='Survived')
y = train['Survived']

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=42)

clf=LogisticRegression(random_state=0, max_iter=1000).fit(X_train, y_train)
preds_valid=clf.predict(X_valid)

scaler = StandardScaler()
scaler.fit(X_train, y_train)
X_train_normed = scaler.transform(X_train)
X_valid_normed = scaler.transform(X_valid)

result_preds=clf.predict(test)
df=pd.DataFrame({'PassengerId': ids.values, 'Survived': result_preds})

df.to_csv('result.csv', index=False)